### ISSUE TITLE
RGB20 & RGB21 tracking issue

### ISSUE THREAD

**Issue by dr-orlovsky** [RGB-WG/rgb-wallet#49]
Finalization of the RGB20 and RGB21 interface involves the following steps:
- [x] Revisiting standards: 
    - [x] https://github.com/LNP-BP/LNPBPs/pull/154
    - [x] https://github.com/LNP-BP/LNPBPs/pull/156
    - [x] https://github.com/LNP-BP/LNPBPs/pull/155
- [x] Completing data type system required to provide RGB20 and RGB21 feature set
    - [x] Definition of new restricted charsets used in interfaces for contract ticker, name, mime types etc: https://github.com/strict-types/strict-encoding/pull/14
    - [x] Amendments to strict encoding library: https://github.com/strict-types/strict-encoding/pull/16
    - [x] Update of standard strict types library: https://github.com/strict-types/strict-types/pull/8
    - [x] Refactoring type lib and system builders to support all necessary syntax and library features: https://github.com/strict-types/strict-types/pull/9
- [x] Update all existing libs to the amended syntax:
    - [x] Finalization of CommitVerify type library: https://github.com/LNP-BP/client_side_validation/pull/122
    - [x] Finalization of Bitcoin and BPCore type libraries https://github.com/BP-WG/bp-core/pull/42
    - [x] Update to AluVM type library: https://github.com/AluVM/rust-aluvm/commit/a996c887060534406699d50742bad8751a6486ba
    - [x] Update to RGBCore type library: https://github.com/RGB-WG/rgb-core/pull/155
    - [x] Finalization of RGBContracts type library: https://github.com/RGB-WG/rgb-wallet/pull/48/commits/408b8f493db401efadfe4b2a29df4b5acd331c3f
- [x] Creation of strict types registry hosting libraries used in constructing RGB interfaces: https://github.com/strict-types/registry
- [x] RGB20 and RGB21 interfaces: https://github.com/RGB-WG/rgb-wallet/pull/48
- [x] Simple schema based on RGB20 and RGB21 implementing interfaces: https://crates.io/crates/rgb-schemata

**Comment by dr-orlovsky** [comment]
Closing with the release of https://github.com/RGB-WG/rgb-wallet/tree/v0.10.2 and https://github.com/RGB-WG/rgb-schemata/tree/v0.10.0-beta.1
